name: Bump Version & Changelog PR Validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  bump-and-validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and ensure all branches are available
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure we have full commit history for changelog generation

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install git-cliff using taiki-e/install-action
      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0

      # Bump version and generate changelog
      - name: Bump version and generate changelog
        run: |
          # Bump the version (patch version)
          VERSION=$(npm version patch --no-git-tag-version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Generate changelog using git-cliff
          git-cliff -o CHANGELOG.md

          # Commit changes: version bump and changelog
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore: bump version to v$VERSION and update changelog"

      # Run any necessary validation (tests, linting, etc.)
      - name: Run validations
        run: npm run test

      # Add a comment in the PR saying it's ready to deploy
      - name: Add 'Ready to deploy' comment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body": "Ready to deploy!"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      # Push the changes (version bump and changelog) to the same PR branch
      - name: Push changes with version bump and changelog
        run: git push origin HEAD:${{ github.head_ref }}
