name: Bump Version and Update Changelog in Pre-Release

on:
  pull_request:
    branches:
      - pre-release/*
    types: [opened, synchronize, reopened]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout pre-release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff for changelog generation
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0

      - name: Generate changelog
        run: |
          git-cliff -o CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Bump version in package files
        run: |
          # Update version in package.json or other files that contain versioning information
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.VERSION }}\"/" package.json

      - name: Commit version bump and changelog
        run: |
          git add CHANGELOG.md package.json
          git commit -m "Bump version to ${{ env.VERSION }} and update changelog"
          git push origin pre-release/${{ env.VERSION }}
