name: Check PR Base Branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (requerido para que gh funcione correctamente)
        uses: actions/checkout@v3

      - name: Check and change base branch if targeting main
        if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "⚠️ PR #${{ github.event.pull_request.number }} targets 'main'. Changing base to 'develop'..."
          gh pr edit ${{ github.event.pull_request.number }} --base develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
