name: Create Pre-Release PR from Develop to Pre-Release Branch

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag (current version)
        id: get_version
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Calculate next version
        id: next_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${CURRENT_VERSION#v}"
          NEXT_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Create pre-release branch
        run: |
          git checkout -b pre-release/${VERSION}
          git push origin pre-release/${VERSION}

      - name: Create PR from develop to pre-release branch
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          title: "Pre-Release ${VERSION} - Prepare release"
          body: "This PR prepares the release ${VERSION} from `develop` to `pre-release`."
          base: pre-release/${VERSION}
          branch: develop
          delete-branch: false
