name: Create Pre-Release PR from Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version tag
        id: get_version
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Calculate next version
        id: next_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${CURRENT_VERSION#v}"
          NEXT_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"
          echo "VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Create pre-release branch
        run: |
          git checkout -b pre-release/${{ env.VERSION }}
          git push origin pre-release/${{ env.VERSION }}

      - name: Create PR from develop to pre-release
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Pre-Release ${{ env.VERSION }} - Prepare release"
          body: "This PR prepares the release ${{ env.VERSION }} from `develop` to `pre-release`."
          base: pre-release/${{ env.VERSION }}
          branch: develop
