# .github/workflows/pr-validation.yml

name: PR Validation (Develop → Main)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    # Trigger the workflow when a PR from `develop` to `main` is created or updated.

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run build (and tests)
        run: |
          npm run build
          # Run tests if applicable:
          npm run test

      - name: Check for version bump
        run: |
          VERSION_BUMP=$(git log --grep="chore: bump version" --oneline)
          if [ -z "$VERSION_BUMP" ]; then
            echo "No version bump found in this PR"
            exit 1  # Fails the workflow if there's no version bump
          fi
        continue-on-error: true

      - name: Add "Ready to deploy" comment to PR
        if: success() && steps.check-for-version-bump.outcome == 'success'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="Ready to deploy"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"

      - name: Fail workflow if version bump is missing
        if: failure()
        run: exit 1
