# .github/workflows/sync-main-to-develop.yml

name: Sync main to develop

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
    # This will trigger the workflow when the "Deploy to GitHub Pages" workflow completes.

jobs:
  sync-main-to-develop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commits to avoid potential issues with history.

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch All Branches
        run: |
          git fetch origin main
          git fetch origin develop

      - name: Create Pull Request to Sync main → develop
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync main into develop"
          title: "🔄 Sync main to develop"
          body: "This PR merges the latest changes from `main` into `develop`."
          base: develop
          branch: sync/main-to-develop
          delete-branch: true
          # Automatically delete the branch after the PR is merged.
