name: Sync Main to Develop

on:
  pull_request:
    branches:
      - main
    types: [merged]

jobs:
  sync-main-to-develop:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.pull_request.merged == 'true'
    steps:
      - name: Checkout main and develop branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch origin main
          git fetch origin develop

      - name: Create PR to sync main → develop
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          commit-message: "Sync main into develop"
          title: "🔄 Sync main to develop"
          body: "This PR merges the latest changes from `main` into `develop`."
          base: develop
          branch: sync/main-to-develop
          delete-branch: true
