name: Sync main to develop

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin develop

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge origin/main
          git push origin develop
