name: Update Changelog After Deployment

on:
  push:
    branches:
      - main
  deployment_status:
    types: [success]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create bump branch from main
        run: |
          git checkout main
          git pull origin main
          git checkout -b bump-changelog-branch

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0  # Install git-cliff to generate changelog

      - name: Generate changelog
        run: |
          git-cliff -o CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit changelog and push to bump branch
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog after deployment to main"
          git push origin bump-changelog-branch

      - name: Create Pull Request from bump to main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: update changelog"
          body: "This PR updates the changelog after the deployment to main."
          base: main
          branch: bump-changelog-branch
          labels: 'ready for merge'
          delete-branch: false

      - name: Verify PR creation
        run: |
          echo "Pull Request created successfully."
