name: Version Bump & Changelog

on:
  pull_request:
    branches:
      - release/*  # Trigger on PRs to release branches (e.g., release/1.0.0)

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0

      - name: Generate changelog
        run: |
          git-cliff -o CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Bump version (patch)
        run: |
          VERSION=$(npm version patch -m "chore: bump version to %s")
          echo "Version bumped to $VERSION"

      - name: Commit version bump and changelog
        run: |
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore: bump version and update changelog"
          git push origin HEAD:${{ github.head_ref }}
