name: Version Bump and Changelog Update

on:
  push:
    branches:
      - main  # This triggers after merging into the `main` branch

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff for changelog generation
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0

      - name: Generate Changelog
        run: |
          git-cliff -o CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: update changelog"

      - name: Bump Version (patch)
        run: |
          VERSION=$(npm version patch -m "chore: bump version to %s")
          git push origin main --tags  # Push the new version tag to `main`

      - name: Push changes and tag
        run: |
          git push origin main --tags
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
