name: Version bump and changelog for develop

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  bump-version-and-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new tag
        run: |
          VERSION=$(npm version patch --no-git-tag-version)
          TAG_NAME="v$(echo $VERSION | sed 's/^v//')"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.7.0

      - name: Generate changelog
        run: |
          git-cliff -o CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Bump version (patch version)
        run: |
          npm version patch -m "chore: bump version to v%s"

      - name: Commit and push version bump and changelog
        run: |
          git add CHANGELOG.md
          git add package.json package-lock.json
          git commit -m "chore: bump version and update changelog"
          git push origin HEAD:develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run validations (build, lint, test)
        run: |
          npm run build
          npm run lint
          npm test
